version: '3.7'

services: 
  database_nest_api:
    image: postgres
    container_name: database_nest_api
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest_api
    volumes:
      - pgdata_nest_api:/data/postgres
    network_mode: host

  app_nest_api:
    build: .
    container_name: app_nest_api
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata_nest_api:
    driver: local